Feature/persist approver decision
blackboard-innersource/explain-bot pull request #2
Opened 2021-07-19 15:03 UTC by ne-cabrerav

2021-07-19 17:29 UTC, oijusti approved these changes

2021-07-21 15:32 UTC, gihernandez requested changes

2021-07-21 15:32 UTC, gihernandez commented on lambda/add_meaning.py
> +    actions=payload.get('actions')
Format: 
actions = payload

2021-07-21 15:32 UTC, gihernandez commented on lambda/add_meaning.py
> +        acronym = payload['message']['blocks'][1]['fields'][0]['text'][12:]
A comment here will be useful! If a new button call or similar is added this will break

2021-07-21 15:32 UTC, gihernandez commented on lambda/add_meaning.py
> +        value=actions[0]['value']
Formar: value = actions

2021-07-21 15:32 UTC, gihernandez commented on lambda/add_meaning.py
> +def approveAcronym(acronym, userId):
**approveAcronym** and **denyAcronym** are almost the same, could you refactor this into a single method with a thirdParameter to avoid duplicated code:

**persistDecision(acronym, userId, decision)**

2021-07-21 16:15 UTC, gihernandez approved these changes

2021-07-21 18:07 UTC, merged