Feature/persist denied acronyms
blackboard-innersource/explain-bot pull request #21
Opened 2021-09-07 19:01 UTC by gihernandez

Persist denied acronyms

2021-09-07 21:35 UTC, jcalero23 approved these changes

2021-09-08 15:08 UTC, oijusti commented
This PR is going to be merge to develop or to main?

2021-09-08 15:12 UTC, jdcepedas commented on lambda/add_meaning.py
> +    table.update_item(
Should this table be the TABLE_DENIED instead of the main table? I don't see something like 
`table = dynamodb.Table(TABLE_DENIED_NAME)` in the lambdas.

2021-09-08 15:13 UTC, oijusti requested changes
Change the base branch

2021-09-08 16:30 UTC, merged